apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../_cache/metallb/config/frr
  - rbac.yaml


namespace: metallb-system
patches:
  - path: controller-webhook-patch.yaml
  - path: webhookcainjection-patch.yaml
  - path: crd-conversion-patch.yaml
  - path: crdcainjection-patch.yaml
  - path: webhookservicecainjection_patch.yaml
  - path: permission-patch.yaml
