# This patch add annotation to the webhook service config
apiVersion: v1
kind: Service
metadata:
  name: metallb-webhook-service
  namespace: system
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: webhook-server-cert
