apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: metallb
    component: webhook-server
  name: webhook-server
  namespace: system
spec:
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: metallb
      component: webhook-server
  template:
    metadata:
      labels:
        app: metallb
        component: webhook-server
    spec:
      containers:
      - args:
        - --webhook-mode=onlywebhook
        - --port=9120
        - --log-level=info
        - --tls-cipher-suites=$(TLS_CIPHER_SUITES)
        - --tls-min-version=$(TLS_MIN_VERSION)
        - --tls-curve-preferences=$(TLS_CURVE_PREFERENCES)
        image: controller
        name: webhook-server
        ports:
        - containerPort: 9120
          name: metricshttps
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 9443
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3
          timeoutSeconds: 1
          successThreshold: 1
        readinessProbe:
          tcpSocket:
            port: 9443
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - all
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        env:
          - name: METALLB_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: METALLB_BGP_TYPE
            value: "native"
          - name: TLS_CIPHER_SUITES
            valueFrom:
              configMapKeyRef:
                name: metallb-tls-config
                key: TLS_CIPHER_SUITES
                optional: false
          - name: TLS_MIN_VERSION
            valueFrom:
              configMapKeyRef:
                name: metallb-tls-config
                key: TLS_MIN_VERSION
                optional: false
          - name: TLS_CURVE_PREFERENCES
            valueFrom:
              configMapKeyRef:
                name: metallb-tls-config
                key: TLS_CURVE_PREFERENCES
                optional: false
      nodeSelector:
        kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      serviceAccountName: controller
      terminationGracePeriodSeconds: 0
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: metallb-webhook-cert
