# TODO: Or deployed by the operator-codebase
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
 name: controller
 namespace: metallb-system
spec:
 podSelector:
   matchLabels:
    app: metallb
    component: controller
 egress:
  - ports:
      - protocol: TCP
        port: 6443
 ingress:
  - ports:
      - protocol: TCP
        port: 9120
 policyTypes:
  - Egress
  - Ingress
---
# speakers are hostnetwork
