apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-server
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: webhook-server
        args:
        - --disable-cert-rotation=true
        - --port=9120
        - --log-level=info
        - --webhook-mode=onlywebhook
        - --tls-cipher-suites=$(TLS_CIPHER_SUITES)
        - --tls-min-version=$(TLS_MIN_VERSION)
        - --tls-curve-preferences=$(TLS_CURVE_PREFERENCES)
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - --enable-leader-election
        - --disable-cert-rotation=true
        - --external-metallb-webhook-server